### PR TITLE
20.22.3 touchup es.js langterm

### PR DESCRIPTION
**Pull request by mostlyfabulous**

### CODE REVIEW

**Comment by dustxd** [comment]
you're a champ Andrew 🏆

**Review by dustxd — DISMISSED** [review]

**Comment by mostlyfabulous** [comment]
Thanks for the 👁️ 👁️

**Comment by mostlyfabulous** [comment]
CI is stuck?

**Comment by dustxd** [comment]
I don't see the workflows being run too :eyes:

**Review by dustxd — DISMISSED** [review]

**Pull request closed without merging**
