### PR TITLE
Translation Updates

### PR DESCRIPTION
**Pull request by AlexBedley**

### CODE REVIEW

**Comment by AlexBedley** [comment]
@mdgbayly not sure exactly who I should add to review the activity-editor and activity-collection-editor langterms.

The quick-eval ones seem good to me however.

**Comment by mdgbayly** [comment]
> @mdgbayly not sure exactly who I should add to review the activity-editor and activity-collection-editor langterms.
> 
@emil-furniss Would you be able to take a quick skim through the translations to double check that it looks like we got translations for all the `d2l-activity-editor` related terms.

Thanks!

**Comment by mdgbayly** [comment]
activity-collection-editor is probably someone from the learning paths team .e.g. @m6jones

**Comment by AlexBedley** [comment]
I have updated this PR to make the linter ignore all `.js` files that are in folders called `lang`

**Pull request merged**
