### PR TITLE
fix overtranslation of korean langterms

### PR DESCRIPTION
**Pull request by maboelsoudd2l**
It seems that the translators did not translate it properly, we will have to ask them to retranslate them. At this point I'm just doing damage control so that the master branch wouldn't crash when the language is switched to korean. 

I also did a rough check in all the other languages to see if this problem exists elsewhere but didn't find anything else.

### CODE REVIEW

**Comment by Surekh** [comment]
Thanks, @maboelsoudd2l. We had shared specific instructions for translators to support translating this specific term (ICU format), it looks like it was not followed for Korean. Let us merge this fix and Tina will be following up with the translation team to get a new Korean translation for this term.

**Comment by maboelsoudd2l** [comment]
lol Alex `other` is the only thing it shouldn't translate 😆

**Comment by maboelsoudd2l** [comment]
image
So this is a screenshot of a typical ICU message
The "one", "other" are part of the syntax, they shouldn't be translated, just like the variables we use

**Comment by AlexBedley** [comment]
Ah ok I get it. thanks!

**Pull request merged**
