### PR TITLE
update edit in place to 1.0.8

### PR DESCRIPTION
**Pull request by iFun**

### CODE REVIEW

**Comment by AKobets** [comment]
travisci build is failing with error `No matching version found for @brightspace-ui-labs/edit-in-place@^1.0.8`

**Comment by iFun** [comment]
> travisci build is failing with error `No matching version found for @brightspace-ui-labs/edit-in-place@^1.0.8`

I published a new release for the repo is there anything else i need to do?

**Comment by iFun** [comment]
> You edited the package.json of edit-in-place to be 1.0.8 but did not update the npm registry: https://www.npmjs.com/package/@brightspace-ui-labs/edit-in-place
> Please review the Versioning, Releasing & Deploying section at the bottom of the edit-in-place repo:
> 
> `Versioning, Releasing & Deploying All version changes should obey semantic versioning rules. Include either [increment major], [increment minor] or [increment patch] in your merge commit message to automatically increment the package.json version, create a tag, and trigger a deployment to NPM.`
> 
> I would recommend deleting your commit, making a new commit (possibly using `git commit --allow-empty` if there's nothing to actually commit) and then in the merge commit message, entering `[increment patch]` to update it to 1.0.8 and publish to NPM. In the future, do this on your original merge whenever you change the code.

I see. in the past we just publish a new release and edit package-lock the new version would installed automatically in the package

**Comment by iFun** [comment]
@BhamelinD2L I think the API key we have is incorrect for the CI. it failed to deploy because missing api_key

**Comment by m6jones** [comment]
> @BhamelinD2L I think the API key we have is incorrect for the CI. it failed to deploy because missing api_key

We should update it to use our team key.

**Comment by iFun** [comment]
> > @BhamelinD2L I think the API key we have is incorrect for the CI. it failed to deploy because missing api_key
> 
> We should update it to use our team key.

I talked to Dave L He told me to disable the new BETA feature on Travis CI(“Enable build config validation” ) and it worked. It is because Travis is getting ready to switch over to a new config file format and this toggle is supposed to be checking against that ahead of time.

**Pull request merged**
