### PR TITLE
Use environment variables instead of direct injection in backport workflow

### LINKED ISSUE #2135: Security issue
See https://github.com/Brightspace/d2l-class-stream/issues/1289

### PR DESCRIPTION
**Pull request by awikkerink**
Fixes #2135

### CODE REVIEW

**Comment by awikkerink** [comment]
/backport '+`'+(await (async function() {console.log('Hi');
await github.issues.createComment({
  issue_number: context.payload.issue.number,
  owner: context.repo.owner,
  repo: context.repo.repo,
  body: "I'm the very model of a modern major general"
});
; return ''})())+'`; //

Fixes this ^

**Comment by awikkerink** [comment]
/backport '+`'+(await (async function() {console.log('Hi');
await github.issues.createComment({
  issue_number: context.payload.issue.number,
  owner: context.repo.owner,
  repo: context.repo.repo,
  body: "I'm the very model of a modern major general"
});
; return ''})())+'`

Fixes this ^

**Comment by awikkerink** [comment]
/backport '+`'+(await (async function() {console.log('Hi');
await github.issues.createComment({
  issue_number: context.payload.issue.number,
  owner: context.repo.owner,
  repo: context.repo.repo,
  body: "I'm the very model of a modern major general"
});
; return ''})())+'`; //

**Comment by awikkerink** [comment]
Fixes ^

**Comment by awikkerink** [comment]
Also fixes https://github.com/BrightspaceHypermediaComponents/activities/pull/2148#issuecomment-966391110

**Review by njostonehouse — APPROVED** [review]

**Comment by awikkerink** [comment]
Could someone with write permissions please merge?

**Comment by awikkerink** [comment]
@njostonehouse could you merge?

**Comment by mdulat** [comment]
@awikkerink it's failing CI, do you know why? Looks like access issues.

**Comment by awikkerink** [comment]
It's because it's a fork.

**Comment by mdulat** [comment]
> It's because it's a fork.

Ah ok, so someone with admin permissions can merge (I cannot because of the failed tests).
Alternatively I can open a PR with your changes from a not-fork.

**Comment by mdulat** [comment]
Replaced by https://github.com/BrightspaceHypermediaComponents/activities/pull/2153

**Pull request closed without merging**
