### PR TITLE
added translation "view in info on (activity name)" 

### PR DESCRIPTION
**Pull request by maboelsoudd2l**

### CODE REVIEW

**Comment by cbusmand2l** [comment]
I assume we don't get `fi` translations?

**Comment by maboelsoudd2l** [comment]
@cbusmand2l guess not...
also `fi.json` looks awfully like english

**Comment by Surekh** [comment]
Hmm... looks like nothing has changed since last approval. So, looks good to me. Why is Visual Difference Tests taking this long - @DiljotSG? We should resolve that at the earliest to unblock this PR and then backport this PR change to 20.19.10 release.

**Comment by DiljotSG** [comment]
Hi @Surekh, sorry about that but the visual difference tests aren't actually running and won't run until #346 and #352 are merged in. I was still testing the visual difference bot and it happened to mark Mohammed's repo, even though there were no tests running. It is safe to ignore that check and merge it anyway.

**Pull request merged**
