### PR TITLE
Renaming to d2l-quick-eval

### PR DESCRIPTION
**Pull request by jeroach**
**ON HOLD** This seems to be all of the references

### CODE REVIEW

**Comment by jeroach** [comment]
FYI people - if this is going to be a royal PITA then let me know (in terms of merge conflicts)

**Comment by jeroach** [comment]
Demo (see screenshot) and tests seem to work.
quick-eval

**Comment by svanherk** [comment]
I'd really like https://github.com/BrightspaceHypermediaComponents/activities/pull/60 in first

**Comment by svanherk** [comment]
Shoot, sorry, didn't mean to close 😞  Just wanted to comment

**Comment by mtjandra** [comment]
I would like to hold of for now as well to avoid merge conflicts and having to migrate in LMS

**Comment by jeroach** [comment]
Okay will put this on hold for now.

**Pull request closed without merging**
