### PR TITLE
Add lang terms for UI search results hotfix

### PR DESCRIPTION
**Pull request by jeroach**
Just getting the lang terms in now, so they can get to translators sooner. 

Still working on the actual fix - that will be a follow up PR

### CODE REVIEW

**Comment by CarolBusman** [comment]
In @AlexBedley 's testing of the search, he identified that we would need to change the placeholder text on the search bar to "Search For" instead of "Search". Would it make sense to get that into this PR so that we can get that to translations as well?

**Comment by mtjandra** [comment]
If the langterms are required for hotfix, I think you will want to sync with Jeff. I believe translations have already gone out.

**Comment by mtjandra** [comment]
Also if needed to go into cert, you will want to follow up with PR to `release/20.19.5` as well

**Comment by jeroach** [comment]
> In @AlexBedley 's testing of the search, he identified that we would need to change the placeholder text on the search bar to "Search For" instead of "Search". Would it make sense to get that into this PR so that we can get that to translations as well?

Since these are for a hotfix, and I assume this would be an update to an existing lang term, instead of a new term, then the "Search For" text would also get hotfixed. If we're good with that then cool. But want to confirm

**Pull request merged**
