### PR TITLE
Update readme so tests can run again!

### PR DESCRIPTION
**Pull request by m6jones**

### CODE REVIEW

**Comment by m6jones** [comment]
I need better page for how to setup Artifactory. I already set it up on both my computers. Not sure how I did it anymore.

**Comment by jeroach** [comment]
Can this happen automatically via `npm i` - e.g. saved as a dev dependency?

**Comment by jeroach** [comment]
FYI this does work locally :) Just wondering if we can skip a step

**Comment by m6jones** [comment]
Sadly it doesn't seem to be working for everyone. Will look into make it better.

**Comment by m6jones** [comment]
Disabling attest right now seems to be the best option :(

**Pull request closed without merging**
