### PR TITLE
Vy/singular resubmission counts

### PR DESCRIPTION
**Pull request by vix633**
Tests coming in another PR, I'd like to get this on quad as soon as we're good with this review.

### CODE REVIEW

**Comment by mtjandra** [comment]
You should be able to do all this with ICU syntax, see https://formatjs.io/guides/message-syntax/#plural-format

Ex:

Assignments
```
You have {resub, plural,
    =0 {{newNum} new, 0 resubmissions}
    one {{newNum} new, 1 resubmission}
    other {{newNum} new, {resub} resubmissions}
}
```

Discussions
```
You have {numInteractions, plural,
    =0 {0 threads or replies}
    one {1 thread or reply}
    other {{numInteractions} threads or replies}
}
```

Quiz
```
You have {reAttemptNum, plural,
    =0 {{newNum} new, 0 reattempts}
    one {{newNum} new, 1 reattempt}
    other {{newNum} new, {reAttemptNum} reattempts}
}.
```

**Comment by maboelsoudd2l** [comment]
@mtjandra how would we do it with lang terms in mind though?

**Comment by svanherk** [comment]
This is a format our translators understand, and `d2l-localize` should support.
Example returned from translators: https://github.com/BrightspaceHypermediaComponents/sequences/blob/master/locales.json#L23

**Comment by mtjandra** [comment]
To be fair it will be complicated for them I think. It will likely come back wrong first time around, but maybe I'm being pessimistic. Just going to test out https://github.com/BrightspaceHypermediaComponents/activities/pull/310 right now

**Comment by svanherk** [comment]
> To be fair it will be complicated for them I think. It will likely come back wrong first time around, but maybe I'm being pessimistic. Just going to test out #310 right now

True, when I said "understand", I guess I meant "are supposed to understand and have seen before"

**Comment by maboelsoudd2l** [comment]
This PR is outdated because logic has already been implemented by https://github.com/BrightspaceHypermediaComponents/activities/pull/310

**Comment by vix633** [comment]
> You should be able to do all this with ICU syntax, see https://formatjs.io/guides/message-syntax/#plural-format
> 
> Ex:
> 
> Assignments
> 
> ```
> You have {resub, plural,
>     =0 {{newNum} new, 0 resubmissions}
>     one {{newNum} new, 1 resubmission}
>     other {{newNum} new, {resub} resubmissions}
> }
> ```
> 
> Discussions
> 
> ```
> You have {numInteractions, plural,
>     =0 {0 threads or replies}
>     one {1 thread or reply}
>     other {{numInteractions} threads or replies}
> }
> ```
> 
> Quiz
> 
> ```
> You have {reAttemptNum, plural,
>     =0 {{newNum} new, 0 reattempts}
>     one {{newNum} new, 1 reattempt}
>     other {{newNum} new, {reAttemptNum} reattempts}
> }.
> ```
> 
> This way you should be able to re-use your lang terms, and no need for your own pluralization logic

Wow, thank god.

**Pull request closed without merging**
