### PR TITLE
Jroach/us112192

### PR DESCRIPTION
**Pull request by jeroach**
[US112192](https://rally1.rallydev.com/#/detail/userstory/353901460400?fdp=true): [Dismiss][UI] Hide dismiss filter from filter component

Thoughts on visual diff tests? Is there a way for me to have the activities list open with the filters open? I think that would be the only way it would work

### CODE REVIEW

**Comment by cbusmand2l** [comment]
I would think that the visdiff tests for filter whitelists would belong in the filter component itself, with unit tests here to be sure we're assigning the whitelist properly.

If we do want to do the visdiff here though, we can manually open the dropdown in the test with `page.evaluate`.

**Comment by jeroach** [comment]
> with unit tests here to be sure we're assigning the whitelist properly.

I think I've covered this - please let me know if not.

> I would think that the visdiff tests for filter whitelists would belong in the filter component itself

Thoughts @AlexBedley ?

**Comment by cbusmand2l** [comment]
> > with unit tests here to be sure we're assigning the whitelist properly.
> 
> I think I've covered this - please let me know if not.

Yes! Sorry, I meant that the unit tests that you've already got in this PR are what we want.

**Comment by AlexBedley** [comment]
I agree with Carol, we should assume the whitelist works correctly, it's up to the filter component to test that.

We just need to validate that we are sending the correct whitelist to the filter component. which that test is basically doing. I'm ok with the current test coverage.

**Pull request merged**
