### PR TITLE
DE43998: [cert] Hide display options for non-embeddable LTI links

### PR DESCRIPTION
**Pull request by brissons**
## Relevant Rally Links

[DE43998](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fdefect%2F601841380817&fdp=true): [cert] LTI page - Add link to LTI link entity that will check X-Frame-Options header

## Description

Backport of https://github.com/BrightspaceHypermediaComponents/activities/pull/1808 for 20.21.7.

### CODE REVIEW

**Review by quinnbudan — COMMENTED** [review]
Should we be backporting the golden updates? Does it apply to this already released version too because it's a tool updated outside of this repo or something?

**Comment by jeroach** [comment]
> Should we be backporting the golden updates? Does it apply to this already released version too because it's a tool updated outside of this repo or something?

Yeah I agree - this change looks like it has nothing to do with the `d2l-quick-eval-widget`

**Comment by brissons** [comment]
> Should we be backporting the golden updates? Does it apply to this already released version too because it's a tool updated outside of this repo or something?

Yes that's correct. There was an update to the visual-diff GitHub action which will show small pixel changes. Not updating the goldens will result in the visual-diff tests failing (I tested on a draft PR and confirmed this).

**Comment by jeroach** [comment]
> > Should we be backporting the golden updates? Does it apply to this already released version too because it's a tool updated outside of this repo or something?
> 
> Yes that's correct. There was an update to the visual-diff GitHub action which will show small pixel changes. Not updating the goldens will result in the visual-diff tests failing (I tested on a draft PR and confirmed this).

Ah I see, very well then :)

**Review by quinnbudan — APPROVED** [review]

**Pull request merged**
