### PR TITLE
fix skeleton label spacing

### PR DESCRIPTION
**Pull request by stevenao**

### CODE REVIEW

**Comment by mostlyfabulous** [comment]
LGTM @mdgbayly thoughts?
image

**Comment by mdgbayly** [comment]
I think we need to replace the `display: block` or other labels will be rendered at 100% width? I think it's sort of working of the score label to the fact that the score component is probably rendered i some kind of flex box?

**Comment by mdgbayly** [comment]
If we don't want to try to use `d2l-input-label` yet (which we probably shouldn't given it's late in the day) maybe we should just remove these label overrides added by Emil. He added them mostly to make the internal date label and other labels consistent. But as we're moving the label outside the date for now, that won't be a problem anymore. The left label panel label bottom margins will still be inconsistent with some of the right panel label bottom margins - but they were not completely consistent with all the right panel labels anyway.

**Comment by stevenao** [comment]
image

**Comment by stevenao** [comment]
> If we don't want to try to use `d2l-input-label` yet (which we probably shouldn't given it's late in the day) maybe we should just remove these label overrides added by Emil. He added them mostly to make the internal date label and other labels consistent. But as we're moving the label outside the date for now, that won't be a problem anymore. The left label panel label bottom margins will still be inconsistent with some of the right panel label bottom margins - but they were not completely consistent with all the right panel labels anyway.
> 
> Did not mean to close ! :-)

yes, the due date label will need to be tweaked.

**Review by mdgbayly — APPROVED** [review]
ok to get this merged and to do any remaining label fix up on follow up PR

**Review by mdgbayly — APPROVED** [review]

**Pull request merged**
